export const products = [
  {
    image: "./src/assets/images/pizza1.jpg",
    category: "product",
  },
  {
    image: "./src/assets/images/pizza2.jpg",
    category: "product",
  }, 
  {
    image: "./src/assets/images/pizza3.jpg",
    category: "product",
  },
  {
    image: "../src/assets/images/grill1.jpg",
    images: [
      "../src/assets/images/grill1.jpg",
      "../src/assets/images/pizza1.jpg",
      "../src/assets/images/pizza2.jpg",
      "../src/assets/images/pizza3.jpg",
    ],
    description: "صحن مشاوي مشكل مع سرفيس كامل وبسعر مناسب",
    category: "swiper",
  },
  {
    image: "../src/assets/images/grill1.jpg",
    images: [
      "../src/assets/images/grill1.jpg",
      "../src/assets/images/pizza1.jpg",
      "../src/assets/images/pizza2.jpg",
      "../src/assets/images/pizza3.jpg",
    ],
    description: "",
    category: "swiper",
  },
  {
    image: "../src/assets/images/grill1.jpg",
    images: [
      "../src/assets/images/grill1.jpg",
      "../src/assets/images/pizza1.jpg",
      "../src/assets/images/pizza2.jpg",
      "../src/assets/images/pizza3.jpg",
    ],
    description: "",
    category: "swiper",
  },
  {
    image: "../src/assets/images/grill1.jpg",
    images: [
      "../src/assets/images/grill1.jpg",
      "../src/assets/images/pizza1.jpg",
      "../src/assets/images/pizza2.jpg",
      "../src/assets/images/pizza3.jpg",
    ],
    description: "",
    category: "swiper",
  },
  {
    image: "../src/assets/images/grill1.jpg",
    images: [
      "../src/assets/images/grill1.jpg",
      "../src/assets/images/pizza1.jpg",
      "../src/assets/images/pizza2.jpg",
      "../src/assets/images/pizza3.jpg",
    ],
    description: "",
    category: "swiper",
  },
  {
    image: "../src/assets/images/pizza1.jpg",
    title: "بيتزا 1",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "pizza",
    caros: "pizza1",
  },
  {
    image: "../src/assets/images/pizza2.jpg",
    title: "بيتزا 2",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "pizza",
    caros: "pizza2",
  },
  {
    image: "../src/assets/images/pizza3.jpg",
    title: "بيتزا 3",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "pizza",
    caros: "pizza3",
  },
  {
    image: "../src/assets/images/pizza4.jpg",
    title: "بيتزا 4",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "pizza",
    caros: "pizza4",
  },
  {
    image: "../src/assets/images/pizza2.jpg",
    title: "بيتزا 4",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "pizza",
    caros: "pizza4",
  },
  {
    image: "../src/assets/images/pizza3.jpg",
    title: "بيتزا 4",
    description: "Lorem ipsum dolor, sit amet consectetur",
    category: "pizza",
    caros: "pizza4",
  },
  {
    image: "/uploads/icons/fakhar.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    image: "./uploads/icons/grillFood.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    image: "/uploads/icons/ham.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    image: "/uploads/icons/seafood.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    image: "/uploads/icons/fakhar.png",
    title: "طبق رئيسي",
    category: "icon",
  },
  {
    image: "../src/assets/images/kunafa.jpg",
    title: "كنافة",
    description: "كنافة على الفحم:\n طريقة عمل الكنافة...",
    price: 90,
    discount: 20,
    category: "offer",
    hasRadius: true,
  },
  {
    image: "../src/assets/images/kunafa.jpg",
    title: "حلاوة الجبن",
    description: "كنافة على الفحم:\n طريقة عمل الكنافة...",
    price: 90,
    discount: 20,
    category: "offer",
  },
  {
    image: "../src/assets/images/kunafa.jpg",
    title: "كنافة",
    description: "طريقة عمل الكنافة",
    price: 90,
    discount: 20,
    category: "offer",
  },
  {
    image: "../src/assets/images/kunafa.jpg",
    title: "كنافة",
    description: "طريقة عمل الكنافة",
    price: 90,
    discount: 20,
    category: "offer",
  },
  {
    image: "../src/assets/images/kunafa.jpg",
    title: "كنافة",
    description: "طريقة عمل الكنافة",
    price: 90,
    discount: 20,
    category: "offer",
  },
];